roboflow:
  api_key: 'API_KEY'
  model: vacuum-challenge
  version: 5
video:
  filename: 'PATH TO VIDEO FILE'
  object_track: robot # robot or vacuum
output:
  save_output: True
  save_path: output_video.mp4